(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require HighOrd.

(* Why3 assumption *)
Definition associativity {m:Type} {m_WT:WhyType m} (op:m -> m -> m) : Prop :=
  forall (x:m) (y:m) (z:m), (((op x) ((op y) z)) = ((op ((op x) y)) z)).

(* Why3 assumption *)
Definition neutral {m:Type} {m_WT:WhyType m} (op:m -> m -> m) (e:m) : Prop :=
  forall (x:m), (((op x) e) = x) /\ (((op e) x) = x).

(* Why3 assumption *)
Definition monoid {m:Type} {m_WT:WhyType m} (op:m -> m -> m) (e:m) : Prop :=
  (associativity op) /\ (neutral op e).

Axiom neutral_unicity :
  forall {m:Type} {m_WT:WhyType m},
  forall (op:m -> m -> m) (e:m), (monoid op e) -> forall (x:m),
  (neutral op x) -> (x = e).

