(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require HighOrd.
Require set.Set.
Require map.Map.
Require map.Const.

Axiom rreal : Type.
Parameter rreal_WhyType : WhyType rreal.
Existing Instance rreal_WhyType.

Parameter setrreal: rreal -> bool.

Parameter rzero: rreal.

Parameter rone: rreal.

Parameter rtwo: rreal.

Axiom oneIsNotZero : ~ (rone = rzero).

Axiom twoIsNotOne : ~ (rtwo = rone).

Axiom twoIsNotZero : ~ (rtwo = rzero).

