(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require HighOrd.
Require set.Set.
Require map.Map.
Require map.Const.

Axiom rreal : Type.
Parameter rreal_WhyType : WhyType rreal.
Existing Instance rreal_WhyType.

Parameter setrreal: rreal -> bool.

Parameter rzero: rreal.

Parameter rone: rreal.

Parameter rtwo: rreal.

Axiom oneIsNotZero : ~ (rone = rzero).

Axiom twoIsNotOne : ~ (rtwo = rone).

Axiom twoIsNotZero : ~ (rtwo = rzero).

(* Why3 assumption *)
Definition rel (a:Type) (b:Type) := (a* b)%type -> bool.

Parameter power:
  forall {a:Type} {a_WT:WhyType a}, (a -> bool) -> (a -> bool) -> bool.

Axiom mem_power :
  forall {a:Type} {a_WT:WhyType a},
  forall (x:a -> bool) (y:a -> bool),
  (set.Set.mem x (power y)) <-> (set.Set.subset x y).

Parameter leq: rreal -> rreal -> Prop.

Parameter lt: rreal -> rreal -> Prop.

Parameter gt: rreal -> rreal -> Prop.

Axiom Refl : forall (x:rreal), leq x x.

Axiom Trans :
  forall (x:rreal) (y:rreal) (z:rreal), (leq x y) -> (leq y z) -> leq x z.

Axiom Antisymm :
  forall (x:rreal) (y:rreal), (leq x y) -> (leq y x) -> (x = y).

Axiom Total : forall (x:rreal) (y:rreal), (leq x y) \/ (leq y x).

Axiom zeroLtOne : lt rzero rone.

Axiom oneLtTwo : lt rone rtwo.

Axiom rrealStar : Type.
Parameter rrealStar_WhyType : WhyType rrealStar.
Existing Instance rrealStar_WhyType.

Parameter x: rrealStar -> rreal.

Axiom rrealStar'invariant : forall (self:rrealStar), ~ ((x self) = rzero).

Parameter rrealPlus: rreal -> bool.

Parameter rrealMinus: rreal -> bool.

Parameter rrealPlusStar: rreal -> bool.

Parameter rrealMinusStar: rreal -> bool.

(* Why3 assumption *)
Definition notRzero (x1:rreal) : Prop := ~ (x1 = rzero).

Parameter infix_plmngt:
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b}, (a -> bool) ->
  (b -> bool) -> ((a* b)%type -> bool) -> bool.

Axiom mem_function :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (f:(a* b)%type -> bool) (s:a -> bool) (t:b -> bool),
  (set.Set.mem f (infix_plmngt s t)) <->
  ((forall (x1:a) (y:b), (set.Set.mem (x1, y) f) ->
    (set.Set.mem x1 s) /\ (set.Set.mem y t)) /\
   forall (x1:a) (y1:b) (y2:b),
   ((set.Set.mem (x1, y1) f) /\ (set.Set.mem (x1, y2) f)) -> (y1 = y2)).

Axiom domain_function :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (f:(a* b)%type -> bool) (s:a -> bool) (t:b -> bool) (x1:a) (y:b),
  (set.Set.mem f (infix_plmngt s t)) -> (set.Set.mem (x1, y) f) ->
  set.Set.mem x1 s.

Axiom range_function :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (f:(a* b)%type -> bool) (s:a -> bool) (t:b -> bool) (x1:a) (y:b),
  (set.Set.mem f (infix_plmngt s t)) -> (set.Set.mem (x1, y) f) ->
  set.Set.mem y t.

Axiom function_extend_range :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (f:(a* b)%type -> bool) (s:a -> bool) (t:b -> bool) (u:b -> bool),
  (set.Set.subset t u) -> (set.Set.mem f (infix_plmngt s t)) ->
  set.Set.mem f (infix_plmngt s u).

Axiom function_reduce_range :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (f:(a* b)%type -> bool) (s:a -> bool) (t:b -> bool) (u:b -> bool),
  (set.Set.subset u t) -> (set.Set.mem f (infix_plmngt s t)) ->
  (forall (x1:a) (y:b), (set.Set.mem (x1, y) f) -> set.Set.mem y u) ->
  set.Set.mem f (infix_plmngt s u).

Parameter inverse:
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  ((a* b)%type -> bool) -> (b* a)%type -> bool.

Axiom Inverse_def :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (r:(a* b)%type -> bool), forall (x1:a) (y:b),
  (set.Set.mem (y, x1) (inverse r)) <-> (set.Set.mem (x1, y) r).

Parameter dom:
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  ((a* b)%type -> bool) -> a -> bool.

Axiom dom_def :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (r:(a* b)%type -> bool), forall (x1:a),
  (set.Set.mem x1 (dom r)) <-> exists y:b, set.Set.mem (x1, y) r.

Parameter ran:
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  ((a* b)%type -> bool) -> b -> bool.

Axiom ran_def :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (r:(a* b)%type -> bool), forall (y:b),
  (set.Set.mem y (ran r)) <-> exists x1:a, set.Set.mem (x1, y) r.

Parameter infix_mnmngt:
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b}, (a -> bool) ->
  (b -> bool) -> ((a* b)%type -> bool) -> bool.

Axiom mem_total_functions :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (f:(a* b)%type -> bool) (s:a -> bool) (t:b -> bool),
  (set.Set.mem f (infix_mnmngt s t)) <->
  ((set.Set.mem f (infix_plmngt s t)) /\ (set.Set.infix_eqeq (dom f) s)).

Axiom total_function_is_function :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (f:(a* b)%type -> bool) (s:a -> bool) (t:b -> bool),
  (set.Set.mem f (infix_mnmngt s t)) -> set.Set.mem f (infix_plmngt s t).

Parameter apply:
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  ((a* b)%type -> bool) -> a -> b.

Axiom apply_def1 :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (f:(a* b)%type -> bool) (s:a -> bool) (t:b -> bool) (a1:a),
  ((set.Set.mem a1 s) /\ (set.Set.mem f (infix_mnmngt s t))) ->
  set.Set.mem (a1, apply f a1) f.

Axiom apply_def2 :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (f:(a* b)%type -> bool) (s:a -> bool) (t:b -> bool) (a1:a) (b1:b),
  ((set.Set.mem f (infix_mnmngt s t)) /\ (set.Set.mem (a1, b1) f)) ->
  (b1 = (apply f a1)).

Axiom injection :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (f:(a* b)%type -> bool) (s:a -> bool) (t:b -> bool),
  forall (x1:a) (y:a), (set.Set.mem f (infix_mnmngt s t)) ->
  (set.Set.mem (inverse f) (infix_plmngt t s)) -> (set.Set.mem x1 s) ->
  (set.Set.mem y s) -> ((apply f x1) = (apply f y)) -> (x1 = y).

Parameter times:
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b}, (a -> bool) ->
  (b -> bool) -> (a* b)%type -> bool.

Axiom times_def :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (a1:a -> bool) (b1:b -> bool) (x1:a) (y:b),
  (set.Set.mem (x1, y) (times a1 b1)) <->
  ((set.Set.mem x1 a1) /\ (set.Set.mem y b1)).

(* Why3 assumption *)
Definition relations {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b}
    (u:a -> bool) (v:b -> bool) : ((a* b)%type -> bool) -> bool :=
  power (times u v).

Axiom break_mem_in_add :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (c:(a* b)%type) (s:(a* b)%type -> bool) (x1:a) (y:b),
  (set.Set.mem c (map.Map.set s (x1, y) true)) <->
  ((c = (x1, y)) \/ (set.Set.mem c s)).

Axiom break_power_times :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (r:(a* b)%type -> bool) (u:a -> bool) (v:b -> bool),
  (set.Set.mem r (power (times u v))) <-> (set.Set.subset r (times u v)).

Axiom subset_of_times :
  forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (r:(a* b)%type -> bool) (u:a -> bool) (v:b -> bool),
  (set.Set.subset r (times u v)) <->
  forall (x1:a) (y:b), (set.Set.mem (x1, y) r) ->
  (set.Set.mem x1 u) /\ (set.Set.mem y v).

Parameter plus: (rreal* rreal)%type -> rreal.

Parameter times1: (rreal* rreal)%type -> rreal.

Parameter uminus: rreal -> rreal.

Parameter inverse1: rreal -> rreal.

Parameter minus: (rreal* rreal)%type -> rreal.

Parameter divide: (rreal* rreal)%type -> rreal.

Parameter abs: rreal -> rreal.

Parameter sqrt: rreal -> rreal.

Axiom sqrt_spec :
  forall (x1:rreal), (leq rzero x1) -> ((times1 (sqrt x1, sqrt x1)) = x1).

Axiom minusDef :
  forall (x1:rreal) (y:rreal), ((minus (x1, y)) = (plus (x1, uminus y))).

Axiom inverseDef :
  forall (x1:rreal), ~ (x1 = rzero) -> ((times1 (x1, inverse1 x1)) = rone).

Axiom divideDef :
  forall (x1:rreal) (y:rreal), ~ (y = rzero) ->
  ((divide (x1, y)) = (times1 (x1, inverse1 y))).

Axiom absPos : forall (x1:rreal), leq rzero (abs x1).

Axiom absZero : forall (x1:rreal), (x1 = rzero) -> ((abs x1) = rzero).

Axiom absDef :
  forall (x1:rreal),
  ((lt x1 rzero) -> ((abs x1) = (uminus x1))) /\
  ((lt rzero x1) -> ((abs x1) = x1)).

Axiom absTriangular :
  forall (x1:rreal) (y:rreal),
  leq (abs (plus (x1, y))) (plus (abs x1, abs y)).

Axiom absMinus : forall (x1:rreal), ((abs (uminus x1)) = (abs x1)).

Axiom absMult :
  forall (x1:rreal) (y:rreal),
  ((abs (times1 (x1, y))) = (times1 (abs x1, abs y))).

Axiom sqrtDef :
  forall (x1:rreal), (set.Set.mem x1 rrealPlus) ->
  ((times1 (sqrt x1, sqrt x1)) = x1).

Axiom twoDef : (rtwo = (plus (rone, rone))).

